# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('___unittesthelper__', [dirname(__file__)])
        except ImportError:
            import ___unittesthelper__
            return ___unittesthelper__
        if fp is not None:
            try:
                _mod = imp.load_module('___unittesthelper__', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    ___unittesthelper__ = swig_import_helper()
    del swig_import_helper
else:
    import ___unittesthelper__
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = ___unittesthelper__.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return ___unittesthelper__.SwigPyIterator_value(self)
    def incr(self, n=1): return ___unittesthelper__.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return ___unittesthelper__.SwigPyIterator_decr(self, n)
    def distance(self, *args): return ___unittesthelper__.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return ___unittesthelper__.SwigPyIterator_equal(self, *args)
    def copy(self): return ___unittesthelper__.SwigPyIterator_copy(self)
    def next(self): return ___unittesthelper__.SwigPyIterator_next(self)
    def __next__(self): return ___unittesthelper__.SwigPyIterator___next__(self)
    def previous(self): return ___unittesthelper__.SwigPyIterator_previous(self)
    def advance(self, *args): return ___unittesthelper__.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return ___unittesthelper__.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return ___unittesthelper__.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return ___unittesthelper__.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return ___unittesthelper__.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return ___unittesthelper__.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return ___unittesthelper__.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = ___unittesthelper__.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class UnitTestHelper(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UnitTestHelper, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UnitTestHelper, name)
    __repr__ = _swig_repr
    __swig_setmethods__["someBytes"] = ___unittesthelper__.UnitTestHelper_someBytes_set
    __swig_getmethods__["someBytes"] = ___unittesthelper__.UnitTestHelper_someBytes_get
    if _newclass:someBytes = _swig_property(___unittesthelper__.UnitTestHelper_someBytes_get, ___unittesthelper__.UnitTestHelper_someBytes_set)
    __swig_setmethods__["someNodeId0"] = ___unittesthelper__.UnitTestHelper_someNodeId0_set
    __swig_getmethods__["someNodeId0"] = ___unittesthelper__.UnitTestHelper_someNodeId0_get
    if _newclass:someNodeId0 = _swig_property(___unittesthelper__.UnitTestHelper_someNodeId0_get, ___unittesthelper__.UnitTestHelper_someNodeId0_set)
    __swig_setmethods__["someNodeId1"] = ___unittesthelper__.UnitTestHelper_someNodeId1_set
    __swig_getmethods__["someNodeId1"] = ___unittesthelper__.UnitTestHelper_someNodeId1_get
    if _newclass:someNodeId1 = _swig_property(___unittesthelper__.UnitTestHelper_someNodeId1_get, ___unittesthelper__.UnitTestHelper_someNodeId1_set)
    __swig_setmethods__["someNodeId2"] = ___unittesthelper__.UnitTestHelper_someNodeId2_set
    __swig_getmethods__["someNodeId2"] = ___unittesthelper__.UnitTestHelper_someNodeId2_get
    if _newclass:someNodeId2 = _swig_property(___unittesthelper__.UnitTestHelper_someNodeId2_get, ___unittesthelper__.UnitTestHelper_someNodeId2_set)
    __swig_setmethods__["someExpandedNodeId0"] = ___unittesthelper__.UnitTestHelper_someExpandedNodeId0_set
    __swig_getmethods__["someExpandedNodeId0"] = ___unittesthelper__.UnitTestHelper_someExpandedNodeId0_get
    if _newclass:someExpandedNodeId0 = _swig_property(___unittesthelper__.UnitTestHelper_someExpandedNodeId0_get, ___unittesthelper__.UnitTestHelper_someExpandedNodeId0_set)
    __swig_setmethods__["someExpandedNodeId1"] = ___unittesthelper__.UnitTestHelper_someExpandedNodeId1_set
    __swig_getmethods__["someExpandedNodeId1"] = ___unittesthelper__.UnitTestHelper_someExpandedNodeId1_get
    if _newclass:someExpandedNodeId1 = _swig_property(___unittesthelper__.UnitTestHelper_someExpandedNodeId1_get, ___unittesthelper__.UnitTestHelper_someExpandedNodeId1_set)
    __swig_setmethods__["someExpandedNodeId2"] = ___unittesthelper__.UnitTestHelper_someExpandedNodeId2_set
    __swig_getmethods__["someExpandedNodeId2"] = ___unittesthelper__.UnitTestHelper_someExpandedNodeId2_get
    if _newclass:someExpandedNodeId2 = _swig_property(___unittesthelper__.UnitTestHelper_someExpandedNodeId2_get, ___unittesthelper__.UnitTestHelper_someExpandedNodeId2_set)
    __swig_setmethods__["someQualifiedName0"] = ___unittesthelper__.UnitTestHelper_someQualifiedName0_set
    __swig_getmethods__["someQualifiedName0"] = ___unittesthelper__.UnitTestHelper_someQualifiedName0_get
    if _newclass:someQualifiedName0 = _swig_property(___unittesthelper__.UnitTestHelper_someQualifiedName0_get, ___unittesthelper__.UnitTestHelper_someQualifiedName0_set)
    __swig_setmethods__["someQualifiedName1"] = ___unittesthelper__.UnitTestHelper_someQualifiedName1_set
    __swig_getmethods__["someQualifiedName1"] = ___unittesthelper__.UnitTestHelper_someQualifiedName1_get
    if _newclass:someQualifiedName1 = _swig_property(___unittesthelper__.UnitTestHelper_someQualifiedName1_get, ___unittesthelper__.UnitTestHelper_someQualifiedName1_set)
    __swig_setmethods__["someQualifiedName2"] = ___unittesthelper__.UnitTestHelper_someQualifiedName2_set
    __swig_getmethods__["someQualifiedName2"] = ___unittesthelper__.UnitTestHelper_someQualifiedName2_get
    if _newclass:someQualifiedName2 = _swig_property(___unittesthelper__.UnitTestHelper_someQualifiedName2_get, ___unittesthelper__.UnitTestHelper_someQualifiedName2_set)
    __swig_setmethods__["someLocalizedText"] = ___unittesthelper__.UnitTestHelper_someLocalizedText_set
    __swig_getmethods__["someLocalizedText"] = ___unittesthelper__.UnitTestHelper_someLocalizedText_get
    if _newclass:someLocalizedText = _swig_property(___unittesthelper__.UnitTestHelper_someLocalizedText_get, ___unittesthelper__.UnitTestHelper_someLocalizedText_set)
    __swig_setmethods__["someDateTime"] = ___unittesthelper__.UnitTestHelper_someDateTime_set
    __swig_getmethods__["someDateTime"] = ___unittesthelper__.UnitTestHelper_someDateTime_get
    if _newclass:someDateTime = _swig_property(___unittesthelper__.UnitTestHelper_someDateTime_get, ___unittesthelper__.UnitTestHelper_someDateTime_set)
    def __init__(self): 
        this = ___unittesthelper__.new_UnitTestHelper()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = ___unittesthelper__.delete_UnitTestHelper
    __del__ = lambda self : None;
    def testVariantTypemap_out(self, *args): return ___unittesthelper__.UnitTestHelper_testVariantTypemap_out(self, *args)
    def testVariantTypemap_in(self, *args): return ___unittesthelper__.UnitTestHelper_testVariantTypemap_in(self, *args)
UnitTestHelper_swigregister = ___unittesthelper__.UnitTestHelper_swigregister
UnitTestHelper_swigregister(UnitTestHelper)

# This file is compatible with both classic and new-style classes.


